### ISSUE TITLE
How to Create an Account

### ISSUE THREAD

**Issue by besteffects** [johnhummelAltinity/johnhummelAltinity.github.io#18]
To create an Altinity.Cloud account, visit the Altinity.Cloud info page and select **Request a Test Drive**

Actual result:
I see no Request a Test Drive link on this page. Either the link is wrong, or it is located on a different page.

**Comment by johnhummelAltinity** [comment]
Yup - wrong link.  It's this one:  https://altinity.com/cloud-database/  . Corrected.
