### ISSUE TITLE
How to Configure Cluster Settings

### ISSUE THREAD

**Issue by besteffects** [johnhummelAltinity/johnhummelAltinity.github.io#26]
3. Select Remove to confirm removing the setting.
https://johnhummelaltinity.github.io/altinitycloud/administratorguide/clusters/configurecluster/clusterconfiguresettings/#how-to-delete-an-existing-setting

Actual result:
The button is named OK, not Remove

**Comment by johnhummelAltinity** [comment]
No idea how I missed that.  Corrected.
