### ISSUE TITLE
Migrate Cluster Date

### ISSUE THREAD

**Issue by besteffects** [johnhummelAltinity/johnhummelAltinity.github.io#31]
The section should be named:
Migrate Cluster Data,
not Migrate Cluster Date

**Comment by besteffects** [comment]
Also, cluster migration does not work.

**Comment by johnhummelAltinity** [comment]
I had it right on the link title but not the rest....

OK - if it's not working I'll label this as a Draft document so it doesn't compile for the main site in the future.
