### ISSUE TITLE
CLICKHOUSE ALTINITY STABLE RELEASE™ 20.8.7.15

### ISSUE THREAD

**Issue by besteffects** [johnhummelAltinity/johnhummelAltinity.github.io#33]
The latest stable release is 20.8.11.17
Having our documentation linked to the exact stable version leads to us upgrading this version in documentation constantly.
Maybe we should point out at a time when this version became stable and we should write that newer versions will constantly be released.

**Comment by besteffects** [comment]
However, as I see it now, we are going to update release notes after each Altinity Stable Release. So this issue should not be a problem.

**Comment by johnhummelAltinity** [comment]
That's the plan - i'll keep an eye on it though.
