### ISSUE TITLE
CLICKHOUSE ALTINITY STABLE RELEASE™ 20.8.7.15 table size

### ISSUE THREAD

**Issue by besteffects** [johnhummelAltinity/johnhummelAltinity.github.io#34]
Table overlaps with the right navigation bar.
![image](https://user-images.githubusercontent.com/14294615/103660780-0080b880-4f3c-11eb-83bb-3f8f590bec8b.png)

**Comment by johnhummelAltinity** [comment]
Should be fixed with the other updates to this page.
