### ISSUE TITLE
CLICKHOUSE ALTINITY STABLE RELEASE™ 20.8.7.15 extra lines

### ISSUE THREAD

**Issue by besteffects** [johnhummelAltinity/johnhummelAltinity.github.io#35]
![image](https://user-images.githubusercontent.com/14294615/103660994-3a51bf00-4f3c-11eb-96be-ebb2dcc27ff6.png)

**Comment by johnhummelAltinity** [comment]
Corrected.  Looks like Hugo uses a different markdown than others.
