### ISSUE TITLE
Account Creation and Login

### ISSUE THREAD

**Issue by besteffects** [johnhummelAltinity/johnhummelAltinity.github.io#4]
https://johnhummelaltinity.github.io/altinitycloud/quickstartguide/createaccount/#login-with-auth0
"Once set up, you can click Auth0 to **automatically login**."

Actual result:
You will have to make this setup each time you try to login. In production, it works this way. On new staging, it also started to work this way https://acm.dev.altinity.cloud/
I am not sure if this is a bug or intended behavior, we will need to clarify.

**Comment by johnhummelAltinity** [comment]
I'll modify this to be more generic for now:

> Once set up, you can click Auth0 to authenticate through your Google account.
