### ISSUE TITLE
Runbook Procedures. Wrong tabs

### ISSUE THREAD

**Issue by besteffects** [johnhummelAltinity/johnhummelAltinity.github.io#40]
Actual result:
4. Start with canary updates (one replica, after that one shard).
5. Check that everything works properly after each node upgrade. 3. No errors in logs. 4. Applications healthy

Expected result:
4. Start with canary updates (one replica, after that one shard).
5. Check that everything works properly after each node upgrade. 
     1. No errors in logs. 2. Applications healthy

**Comment by johnhummelAltinity** [comment]
Yes - looks like an error when coming over from Google Docs.  Corrected.
