### ISSUE TITLE
Runbook Procedures. Adding a replica

### ISSUE THREAD

**Issue by besteffects** [johnhummelAltinity/johnhummelAltinity.github.io#41]
Actual result:
Adding a replica to an existing ClickHouse cluster 
Install ClickHouse on a new replica node.
Edit clusters.xml and add node as replica in <shard> to which it will belong.

Expected result:
Adding a replica to an existing ClickHouse cluster 
Install ClickHouse on a new replica node.
Edit clusters.xml and add node as replica in <shard> to which it will belong**s**.

**Comment by johnhummelAltinity** [comment]
I'll disagree here - `to which it will belong` is correct.
